### PR TITLE
Update README.md with port to Julia.

### PR DESCRIPTION
**Pull request by roberthoenig**
I did a port of the overlapping model to Julia -- along with a little heuristic optimization. Hope it's fine to update the README :-)

### CODE REVIEW

**Comment by Yeb03** [comment]
Wrong adress

Il giorno mer 2 gen 2019, 11:54 Robert Hönig <notifications@github.com> ha
scritto:

**Comment by mxgmn** [comment]
Nice! So what is this option (by only propagating constraints locally)?

**Comment by roberthoenig** [comment]
>So what is this option (by only propagating constraints locally)?

In the original algorithm, whenever a field is collapsed, the new constraints on the patterns are propagated with a flood fill algorithm, from field to field, until all fields have a minimum number of possible patterns they could still collapse to. That propagation is very time-consuming. Local constraint propagation limits the flood fill to fields that are within a certain distance  from fully collapsed fields. The idea is that usually, the next field to be collapsed is one that is  adjacent to some other already collapsed field. Thus, it should be fine to only ever propagate constraints wihin a certain radius around the collapsed fields. In practice, I found that there is a trade-off between convergence to a solution and length of the radius. The bigger the radius, the more fields we are going to propagate constraints to (the close it is to the original algorithm), so the more time it takes. I found that with a radius of ~3 fields, the speedup was around x2 - x3, with good convergence until ~40x40. I haven't yet fully examined these ratios for higher radiis.

**Comment by mxgmn** [comment]
I see. So we are trading a single propagation speed with a success rate. How much it speeds up (or if at all) depends very much on the example of course (consider the Chess example where a single nonlocal propagation is enough). I remember Remy proposed it here https://trasevol.dog/2017/09/01/di19/.

**Pull request merged**
