### PR TITLE
Wrong extension or Image Format for output files

### PR DESCRIPTION
**Pull request by pansk**
In this PR I changed the extension. Another fix could be adding a second parameter with System.Drawing.Imaging.ImageFormat.Bmp

### CODE REVIEW

**Comment by pansk** [comment]
It's funny because the Microsoft documentation itself is a bit confused on the subject, and in their code example they use .bmp as extension.
https://msdn.microsoft.com/en-us/library/ktx83wah(v=vs.110).aspx

**Comment by mef51** [comment]
had to make the same change .bmp --> .png

**Comment by pansk** [comment]
I had the problem on Windows 10 and vs2015. Preview didn't complain, but another viewer did.

**Comment by mxgmn** [comment]
@pansk @mef51 Thanks. I moved everything to png. Didn't know that standard library works with pngs.

**Pull request closed without merging**
