### PR TITLE
Remove unused w1 variable in Model.Propagate()

### PR DESCRIPTION
**Pull request by nornagon**

### CODE REVIEW

**Comment by nornagon** [comment]
your avatar!
spiderman-pointing

**Comment by mxgmn** [comment]
=))

Its origin: https://twitter.com/ExUtumno/status/990029767335403522

**Comment by nornagon** [comment]
Oh cool! Mine was created with [BECOME A GREAT ARTIST IN JUST 10 SECONDS](http://ludumdare.com/compo/ludum-dare-27/?action=preview&uid=4987) :D

**Comment by mxgmn** [comment]
Oh wow, that's a brilliant program! I didn't know about it though I know one of the authors.

**Pull request merged**
