### PR TITLE
Add vs2015 solution file.

### PR DESCRIPTION
**Pull request by bostelk**
Set the working directory to "$(OutDir)\..\..\..\..\..\".

### CODE REVIEW

**Comment by CoenraadS** [comment]
The code is nicely cross platform as it is. If a VS file is included, say someone developing on another platform such as osx/linux, and adds a new .cs file to the project, they would have to manually hack it into the VS file. My 2 cents

**Comment by Osyotr** [comment]
Maybe it would be better to have separate branch with VS file included.

**Comment by adamralph** [comment]
A separate branch would need continuous maintenance to keep it updated.

**Comment by ArchimedesPi** [comment]
It's easy enough for people with VS2015 to import it themselves.

**Comment by Broxzier** [comment]
> Set the working directory to "$(OutDir)..........\".

You can manually copy this setting from the `.suo` file to the `.csproj` file, and it will work for everyone.

**Comment by mxgmn** [comment]
I don't want to add VS solution files. This is a console application that depends only on the standard library and with very simple code structure. Closing.

**Pull request closed without merging**
